[tool.poetry]
name = "scriptorium"
version = "0.1.0"
description = ""
authors = ["Luis Giraldo <luisggon@protonmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
jupyter = "^1.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
